name: Generate Quiz Index

on:
  push:
    paths:
      - 'quizzes/*'  # Trigger the action when quiz files are changed or added

jobs:
  generate-index:
    runs-on: ubuntu-latest  # The runner environment
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository's code
        
      - name: List quiz files and generate index.json
        run: |
          # Find all .json files in the /quizzes folder
          quizzes=$(find quizzes -name "*.json" -type f)

          # Generate a JSON array with the file names
          index_json="["
          for quiz in $quizzes; do
            quiz_name=$(basename "$quiz")
            index_json="$index_json\"$quiz_name\","
          done
          # Remove last comma and close the array
          index_json="${index_json%,}]"

          # Write the output to quizzes/index.json
          echo "$index_json" > quizzes/index.json
          
      - name: Commit index.json changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Auto-update index.json for quizzes'
          add: 'quizzes/index.json'
